### ISSUE TITLE
Attempting to compile statically linked binary using musl-libc breaks

### ISSUE THREAD

**Issue by christian-oudard** [mobilecoinofficial/full-service#32]
I'm attempting to run full-service node on Tails. There was a version conflict in glibc, so I'm trying to statically link instead.

```
$ sudo apt install musl-tools
$ rustup target add x86_64-unknown-linux-musl
$ SGX_MODE=SW IAS_MODE=PROD CONSENSUS_ENCLAVE_CSS=$(pwd)/consensus-enclave.css cargo build --release -p mc-full-service --target x86_64-unknown-linux-musl
```

Why is this failing like this?
```
error: failed to run custom build command for `mbedtls-sys-auto v2.18.1 (https://github.com/mobilecoinofficial/rust-mbedtls.git?tag=mc-0.3#8cac1fd1)`

Caused by:
  process didn't exit successfully: `/home/christian/third-party-code/mc-full-service/target/release/build/mbedtls-sys-auto-50549a3b3367f4ab/build-script-build` (exit code: 101)
--- stdout

< 300 lines of cmake >

--- stderr
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_ASM_COMPILER
    CMAKE_ASM_FLAGS
    CMAKE_CXX_COMPILER
    CMAKE_CXX_FLAGS


/usr/include/limits.h:124:16: fatal error: 'limits.h' file not found
/usr/include/limits.h:124:16: fatal error: 'limits.h' file not found, err: true
thread 'main' panicked at 'bindgen error: ()', /home/christian/.cargo/git/checkouts/rust-mbedtls-7d1033e9d0cc8048/8cac1fd/mbedtls-sys/build/bindgen.rs:140:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by christian-oudard** [comment]
I tried compiling for Tails by switching to a Debian Buster VM, which Tails is based on. Interestingly, it failed in the same way trying to do a normal non-musl compile on glibc 2.28. My successful compiles were on glibc 2.32 on Ubuntu.
